### ISSUE TITLE
Error: ExtHandler command occurs every 5 seconds

### ISSUE THREAD

**Issue by theangellmethod** [Microsoft/azserialconsole#58] opened 2018-11-21 23:38 UTC
I am getting an error with the ExtHandler an on Ubuntu 18.04 LTS NC6 VM with the Azure Deep Learning VM image from the marketplace.

2018/11/21 23:30:04.112912 ERROR ExtHandler Command: [pidof systemd-networkd], return code: [1], result: []
2018/11/21 23:30:09.128892 ERROR ExtHandler Command: [pidof systemd-networkd], return code: [1], result: []
2018/11/21 23:30:14.144576 ERROR ExtHandler Command: [pidof systemd-networkd], return code: [1], result: []
2018/11/21 23:30:19.160232 ERROR ExtHandler Command: [pidof systemd-networkd], return code: [1], result: []
2018/11/21 23:30:24.175976 ERROR ExtHandler Command: [pidof systemd-networkd], return code: [1], result: []
2018/11/21 23:30:29.191714 ERROR ExtHandler Command: [pidof systemd-networkd], return code: [1], result: []
2018/11/21 23:30:34.210157 ERROR ExtHandler Command: [pidof systemd-networkd], return code: [1], result: []

**Comment by asinn826** [comment] 2019-01-08 23:36
Closing this issue for now since this is occurring by design. A mitigation may be to use serial console over a separate COM port, and we will take feature into consideration in our backlog. Feel free to reopen if need be.

**Closed by asinn826** 2019-01-08 23:36 UTC

**Comment by nexxai** [comment] 2019-06-17 16:25
How is this "by design"?  I appreciate that these error messages may be important, but just dumping them to the screen is hardly the best way to go about it.  For compliance purposes, we have all port 22 access blocked meaning that for remote management we have to use the serial console, but I keep getting spammed with this stuff.  Is there not a better way to handle this, or allow us (as you suggested) to use a different virtual COM port?

**Comment by asinn826** [comment] 2019-06-20 23:27
@nexxai The serial console service currently connects to only the ttyS0 port on a Linux VM, which also happens to be the same port that the extensions write their error messages to. So since serial console is a service that exists to plumb I/O via ttyS0, it is working as intended. On the other hand, what this results in is a horrible experience where random error messages appear at random times - I've personally experienced it when trying to edit files, which is rather frustrating. FWIW, we've reached out to the team that owns these extensions to see what they can do about making the output less noisy while still being useful. We're also still aware of the work in our backlog to allow users to choose a different COM/ttyS0 port. Hope that helps - unfortunately I don't have a happier response to share yet.

**Comment by asinn826** [comment] 2019-06-21 16:27
There's a bug being tracked here for this issue now: https://github.com/Azure/WALinuxAgent/issues/1465
